sylius_twig_hooks:
  hooks:
    # Admin User Profile form
    'sylius_admin.admin_user.update.content.form.sections#left':
      2fa:
        template: '@BitExpertSyliusTwoFactorAuthPlugin/admin/admin_user/form/2fa.html.twig'

    'sylius_admin.admin_user.update.content.form.sections.2fa':
      content:
        template: '@BitExpertSyliusTwoFactorAuthPlugin/admin/admin_user/form/sections/2fa_active.html.twig'

    'sylius_admin.bitexpert_sylius_twofactor.show.content.header':
      breadcrumbs:
        enabled: false
      title_block:
        enabled: false

    'sylius_admin.bitexpert_sylius_twofactor.show.content':
      main:
        template: '@BitExpertSyliusTwoFactorAuthPlugin/admin/two_factor_setup/main.html.twig'
        priority: 100
