bitexpert_sylius_2fa_admin_setup_2fa_google:
  path: /setup-2fa/google
  methods: [ GET, POST, PUT ]
  defaults:
    _controller: 'BitExpert\SyliusTwoFactorAuthPlugin\Controller\Admin\TwoFactorController::setupGoogleAuth'

bitexpert_sylius_2fa_admin_setup_2fa_qr_code_google:
  path: /setup-2fa/google/qr-code
  methods: [ GET ]
  defaults:
    _controller: 'BitExpert\SyliusTwoFactorAuthPlugin\Controller\Admin\TwoFactorController::displayGoogleAuthenticatorQrCode'

bitexpert_sylius_2fa_admin_setup_2fa_email:
  path: /setup-2fa/email
  methods: [ GET, POST, PUT ]
  defaults:
    _controller: 'BitExpert\SyliusTwoFactorAuthPlugin\Controller\Admin\TwoFactorController::setupEmailAuth'

bitexpert_sylius_2fa_admin_login:
  path: /login/2fa-auth
  defaults:
    _controller: 'scheb_two_factor.form_controller::form'

bitexpert_sylius_2fa_admin_login_check:
  path: /login/2fa-auth-check
