imports:
    - { resource: 'twig_hooks/**/*.yaml' }

scheb_two_factor:
    google:
        enabled: true
        digits: 6
        leeway: 25
        template: '@BitExpertSyliusTwoFactorAuthPlugin/admin/security/two_factor.html.twig'
